# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    cd packages/pwa/
  displayName: 'Change into pwa directory'

- script: |
    npm run save-credentials -- --user y.duckwitz@cosnova.com --key Dbxs-hacPNR5DpZeXNDjtizvLp5RrN54sFeAGVkNSdI
  displayName: 'Prepare credentials for mobify cloud'

- script: |
    npm run push -- -m "$(Build.SourceVersionMessage)"
  displayName: 'Running Tests'